<?php

namespace ContainerJo015bD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LG7ntvOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LG7ntvO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LG7ntvO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.LG7ntvO.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.LG7ntvO": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'entityManager' => '?',
        ]);
    }
}
